### ISSUE TITLE
Problem reporting time spent in method

### ISSUE THREAD

**Issue by jthulhu** [BastouP411/MethodsProfiler#3]
After having added https://github.com/jthulhu/gnocco to the image, try in the playground
```smalltalk
prf := PrfMethodProfiler new.
prf addPackage: #Gnocco asPackage.

objects := GncObjectGraph fuzz: 100.
prf profile: [ result := objects benchIntoFile: 'hello.fuel' ].

prf.
```
The method `GncObjectGraph >> #serialiazeInto:`'s total reported time is 0, yet it's supposed to be (by far) the most expensive one. Running the same code (without the profiler instrumentation) in the usual Pharo debuggers reveals that it takes more than 80% of the whole time.

**Comment by guillep** [comment]
But here the method serializeInto: is not being instrumented. Only the Gnocco package is being instrumented...

Or I'm not understanding the case

**Comment by Mathilde411** [comment]
> But here the method serializeInto: is not being instrumented. Only the Gnocco package is being instrumented...
> 
> Or I'm not understanding the case

`GncObjectGraph >> serializeInto:` is inside the Gnocco package, so it is instrumented

**Comment by jthulhu** [comment]
@guillep `serializeInto:` is part of `Gnocco`, `GncObjectGraph` is a class defined in `Gnocco`. Also, the method is reported no matter the stack used. If the stack is behind a process local variable, then the time reported is wrong.

**Comment by Mathilde411** [comment]
![image](https://github.com/BastouP411/MethodProfiler/assets/28052007/f1f88118-9fcd-4353-b788-14f160f2f881)
Without the ProcessLocalVariable

**Comment by guillep** [comment]
Ok, I found the bug.

Process local state is stored as a weak array. And the call stack of the profiler is stored only in the process local variable. This means that when a GC runs (and that's why this happens with long*ish* executions), the stack is lost. 

Moreover, the stack is now lazily initialized (i.e., if the value is nil), and since the GC puts nil, the stack is re-initialized, masking the error and pushing it for later.

**Comment by guillep** [comment]
With a fix to that, I get the following, is this what is expected?

<img width="1136" alt="imagen" src="https://github.com/BastouP411/MethodProfiler/assets/708322/c171a805-188d-4e88-ba9c-6fd32831cf93">

**Comment by jthulhu** [comment]
I think this is expected. The heavy work is done in an other package, so it's reasonable to have a very long method which doesn't call anything that is profiled.

**Comment by guillep** [comment]
Thanks @jthulhu
